name: show-all-variables

on:
  workflow_dispatch

jobs:
  dump-all:
    name: Dump All GitHub Variables
    runs-on: ubuntu-latest

    steps:
      - name: Dump github context
        run: echo '${{ toJson(github) }}'

      - name: Dump env context
        run: echo '${{ toJson(env) }}'

      - name: Dump job context
        run: echo '${{ toJson(job) }}'

      - name: Dump runner context
        run: echo '${{ toJson(runner) }}'

      - name: Dump strategy context
        run: echo '${{ toJson(strategy) }}'

      - name: Dump matrix context
        run: echo '${{ toJson(matrix) }}'

      - name: Dump steps context
        run: echo '${{ toJson(steps) }}'
